### PR TITLE
Use single S3 client instance per bucket

### PR DESCRIPTION
**Pull request by tues**
Added a new singleton map which stores `AmazonS3Client`s already
created for each S3 bucket so that the clients can be reused. This
avoids creating new connection per each downloaded object, which is
extremely inefficient when thousands of small files are fetched from
the same bucket.

The original sbt plugin does this as well:

https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/396ea80602b572ec44604b8a77dcd3767d30e421/src/main/scala/fm/sbt/S3URLHandler.scala#L248

### CODE REVIEW

**Comment by brian-oclair-aiq** [comment]
I'm ok with approving this.  @MasterDDT any comments?

**Review by MasterDDT — APPROVED** [review]
Lgtm. Just to confirm, `clientCache` isnt being accessed across threads right? The `AmazonS3Client` isn't threadsafe.

**Comment by tues** [comment]
> Lgtm. Just to confirm, `clientCache` isnt being accessed across threads right? The `AmazonS3Client` isn't threadsafe.

@MasterDDT Are you sure about this? I haven't found any mention of that in the official documentation, but 10 years ago it was supposed to be thread-safe: https://forums.aws.amazon.com/message.jspa?messageID=191621

Additionally, there is this `@ThreadSafe` annotation here: https://github.com/aws/aws-sdk-java/blob/e3f18803cac9067e0fbe95805ddb289b02c3408c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L393

**Comment by MasterDDT** [comment]
> > Lgtm. Just to confirm, `clientCache` isnt being accessed across threads right? The `AmazonS3Client` isn't threadsafe.
> 
> @MasterDDT Are you sure about this? I haven't found any mention of that in the official documentation, but 10 years ago it was supposed to be thread-safe: https://forums.aws.amazon.com/message.jspa?messageID=191621
> 
> Additionally, there is this `@ThreadSafe` annotation here: https://github.com/aws/aws-sdk-java/blob/e3f18803cac9067e0fbe95805ddb289b02c3408c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L393

Yes you are right, I misread a code comment we have.

**Pull request merged**
